### ISSUE TITLE
Errors related to OpenCV running it from Dockerfile 

### ISSUE THREAD

**Issue by r-salas** [Telefonica/gymnos#17]
If you run the project from Docker, some errors are thrown because we don't have some packages from Linux installed.

**Comment by r-salas** [comment]
The error is the following:
```sh
Traceback (most recent call last):
  File "bin/scripts/gymnosd.py", line 5, in <module>
    from trainer import Trainer
  File "/home/sysadmin/gymnos/lib/trainer.py", line 7, in <module>
    from dataset_manager import DataSetManager
  File "/home/sysadmin/gymnos/lib/dataset_manager.py", line 5, in <module>
    from dataset_factory import DataSetFactory
  File "/home/sysadmin/gymnos/lib/dataset_factory.py", line 3, in <module>
    from datasets.mnist import *
  File "/home/sysadmin/gymnos/lib/datasets/mnist.py", line 1, in <module>
    import os, subprocess, progressbar, logging, h5py, cv2
  File "/usr/local/lib/python2.7/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by r-salas** [comment]
OpenCV requires 4 additional Linux libraries, if we only want to resize images, maybe we should consider replace OpenCV with another library more lightweight like Pillow.

**Comment by kawaits** [comment]
Going back to original name so related commits are coherent with the issue. An additional issue will be opened to handle the potential migration
